name: Frank Stallone
favicon: null
layout_spectrum: 0.03437228919938207
typography_spectrum: 0.7043887211475521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9127110689878464
  lightness: 0.2553388508968055
  saturation: 0.7665748128201813
  rhythmicContrast: 0.34618172887712717
purpose: []
